version: '3'

services:
  service1:
    image: my-service1-image
    networks:
      - my-network
    environment:
      - SERVICE2_HOST=service2

  service2:
    image: my-service2-image
    networks:
      - my-network

networks:
  my-network:
